# Generated by Django 4.2.7 on 2023-11-12 02:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fname', models.CharField(max_length=200, verbose_name='First Name')),
                ('user_lname', models.CharField(max_length=200, verbose_name='Last Name')),
                ('user_email', models.EmailField(max_length=200, unique=True, verbose_name='Email')),
                ('user_position', models.CharField(max_length=200, verbose_name='Position')),
                ('pub_date', models.DateField(default=datetime.datetime(2023, 11, 12, 2, 51, 3, 252599, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
